name: Synchronize to forked repo
on:
  push:
    branches:
      - develop
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/OZ-Coding-School/oz_externship_fe_04_team2.git
          git fetch upstream develop
          git checkout develop
          git rebase upstream/develop

      - name: Push to fork (this repo)
        env:
         TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git push --force-with-lease \
            "https://x-access-token:${TOKEN}@github.com/miloupark/oz_externship_fe_04_team2.git" \
            develop:develop
